BootstrapMvc.UI/Controllers/FormsController.cs
using System;
using System.IO;
using BootstrapMvc.Core.Controllers;
using BootstrapMvc.UI.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;

namespace BootstrapMvc.UI.Controllers
{
    public class FormsController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BootstrapValidationStyle()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult BootstrapValidationStyle(AddressViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Success("Hooray!");

                return View(viewModel);
            }

            Danger("Looks like something went wrong. Please check your form.");

            return View(viewModel);
        }

        public IActionResult LocalizedForm()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LocalizedForm(OrderViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Success("Hooray!");

                return View(viewModel);
            }

            Danger("Looks like something went wrong. Please check your form.");

            return View(viewModel);
        }

        public IActionResult UploadAndDisplayImage()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UploadAndDisplayImage(IFormFile file)
        {
            if (file.Length > 0)
            {
                var fileName = ContentDispositionHeaderValue
                    .Parse(file.ContentDisposition)
                    .FileName
                    .Trim('"');

                using (var fs = file.OpenReadStream())
                {
                    using (var ms = new MemoryStream())
                    {
                        fs.CopyTo(ms);

                        var fileBytes = ms.ToArray();

                        var s =
                            $"data:image/{Path.GetExtension(fileName).Substring(1)};base64,{Convert.ToBase64String(fileBytes)}";

                        //  save the image to the db
                        //  ...

                        Success("Hooray!");

                        return View(new ImageViewModel
                        {
                            Base64 = s
                        });
                    }
                }
            }

            Danger("Looks like something went wrong. Please check your form.");

            return View();
        }

        public IActionResult ShowHidePassword()
        {
            return View();
        }
    }
}

BootstrapMvc.UI/Views/Forms/BootstrapValidationStyle.cshtml
@{
    ViewData["Title"] = "Bootstrap Validation Style";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>
<p>Use this area to provide additional information.</p>
<ul class="breadcrumb">
    <li><a asp-area="" asp-controller="Forms" asp-action="Index">Forms</a></li>
    <li class="active">Bootstrap Validation Style</li>
</ul>
@await Html.PartialAsync("_Alerts")
<div class="row">
    <div class="col-lg-12">
        <div class="well">
            <form asp-action="BootstrapValidationStyle" asp-controller="Forms" method="post" class="form-horizontal" novalidate="novalidate" id="myForm">
                @await Component.InvokeAsync("Address", new { address = Model })
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script type="text/javascript">
        $(document).ready(function () {

            setFormValidation("myForm");
        })
    </script>
}

BootstrapMvc.UI/Views/Forms/Index.cshtml
@{
    ViewData["Title"] = "Forms";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

<div class="list-group">
    <a asp-area="" asp-controller="Forms" asp-action="BootstrapValidationStyle" class="list-group-item">
        <h4 class="list-group-item-heading">Bootstrap Validation Style</h4>
        <p class="list-group-item-text">Add bootstrap validation styles to ASP.NET MVC form</p>
    </a>
    <a asp-area="" asp-controller="Forms" asp-action="LocalizedForm" class="list-group-item">
        <h4 class="list-group-item-heading">Localized</h4>
        <p class="list-group-item-text">Localized form with globalize.js 1.0.0.</p>
    </a>
    <a asp-area="" asp-controller="Forms" asp-action="UploadAndDisplayImage" class="list-group-item">
        <h4 class="list-group-item-heading">Upload & Display Image</h4>
        <p class="list-group-item-text">Upload and display an image with IFormFile.</p>
    </a>
    <a asp-area="" asp-controller="Forms" asp-action="ShowHidePassword" class="list-group-item">
        <h4 class="list-group-item-heading">Show & Hide Password</h4>
        <p class="list-group-item-text">Show & hide a password with bootstrap-show-password or wit custom code.</p>
    </a>
</div>

BootstrapMvc.UI/Views/Forms/LocalizedForm.cshtml
@using BootstrapMvc.UI.ViewModels
@model OrderViewModel

@{
    ViewData["Title"] = "Localized";
}

<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

<ul class="breadcrumb">
    <li><a asp-area="" asp-controller="Forms" asp-action="Index">Forms</a></li>
    <li class="active">Localized</li>
</ul>

@await Html.PartialAsync("_Alerts")

<div class="row">
    <div class="col-lg-12">
        <div class="well">
            <h4>Globalize demo for the <em id="locale"></em> culture / locale</h4>
            <p>This is a number <strong id="number"></strong> formatted by Globalize: <strong id="numberFormatted"></strong></p>
            <p>This is a date <strong id="date"></strong> formatted by Globalize: <strong id="dateFormatted"></strong></p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="well">
            <form asp-action="LocalizedForm" asp-controller="Forms" method="post" class="form-horizontal" novalidate="novalidate" id="myForm">
                @await Component.InvokeAsync("Order", new { order = Model })
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    @{await Html.RenderPartialAsync("_GlobalizationScriptsPartial"); }
    <script type="text/javascript">
        $(document).ready(function () {

            Globalize.locale("nl");

            var locale = 'nl';
            var number = 12345.67;
            var date = new Date();

            var globalize = Globalize(locale);
            document.querySelector('#locale').innerText = locale;
            document.querySelector('#number').innerText = number;
            document.querySelector('#date').innerText = date;
            document.querySelector('#numberFormatted').innerText = globalize.formatNumber(number, { minimumFractionDigits: 2, useGrouping: true });
            document.querySelector('#dateFormatted').innerText = globalize.formatDate(date, { date: 'long' });

            $('.datepicker').datepicker({
                format: "dd/mm/yyyy",
                todayHighlight: true,
                weekStart: 1,
                todayBtn: true,
                autoclose: true
            });

            setFormValidation("myForm");
        })
    </script>
}

BootstrapMvc.UI/Views/Forms/ShowHidePassword.cshtml
@{
    ViewData["Title"] = "Show & Hide Password";
}

<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

<ul class="breadcrumb">
    <li><a asp-area="" asp-controller="Forms" asp-action="Index">Forms</a></li>
    <li class="active">Show & Hide Password</li>
</ul>

@await Html.PartialAsync("_Alerts")

<div class="well">
    <div class="h2">Using bootstrap-show-password.js</div>
    <form>
        <div class="form-group">
            <label>Username:</label>
            <input type="text" id="username1" name="username1" placeholder="Username" class="form-control">
        </div>
        <div class="form-group">
            <label>Password:</label>
            <input type="password" id="pwd1" name="pwd1" class="form-control" autocomplete="off" placeholder="Password" data-toggle="password">
        </div>
        <div class="form-group">
            <button class="btn btn-success hold">Submit</button>
        </div>
    </form>
</div>

<div class="well">
    <div class="h2">Using custom CSS & Javascript</div>
    <form>
        <div class="form-group">
            <label>Username:</label>
            <input type="text" id="username2" name="username2" placeholder="Username" class="form-control">
        </div>
        <div class="form-group">
            <label>Password:</label>
            <div class="input-append input-group">
                <input type="password" id="pwd2" name="pwd2" class="form-control" autocomplete="off" placeholder="Password">
                <div title="Click here to show/hide password" class="add-on input-group-addon">
                    <label class="show-hide-checkbox">
                        <input type="checkbox" id="show-hide" name="show-hide" />
                        <i class="glyphicon icon-eye-open glyphicon-eye-open unchecked"></i>
                        <i class="glyphicon icon-eye-close glyphicon-eye-close checked"></i>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-success hold">Submit</button>
        </div>
    </form>
</div>


@section Scripts {
    <script>
        (function () {

            var passwordToggler = function (element, field) {
                this.element = element;
                this.field = field;

                this.toggle();
            };

            passwordToggler.prototype = {
                toggle: function () {
                    var self = this;
                    self.element.addEventListener("change", function () {
                        if (self.element.checked) {
                            self.field.setAttribute("type", "text");
                        } else {
                            self.field.setAttribute("type", "password");
                        }
                    }, false);
                }
            };

            document.addEventListener("DOMContentLoaded", function () {
                var checkbox = document.querySelector("#show-hide"),
                    pwd = document.querySelector("#pwd2");

                var toggler = new passwordToggler(checkbox, pwd);
            });

            $("button.hold").on("click", function (event) {
                event.preventDefault();
                event.stopPropagation();
                console.log("Form submission prevented/stopped.");
            });

        })();
    </script>
}

BootstrapMvc.UI/Views/Forms/UploadAndDisplayImage.cshtml
@{
    ViewData["Title"] = "Upload & Display Logo";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>
<p>Use this area to provide additional information.</p>
<ul class="breadcrumb">
    <li><a asp-area="" asp-controller="Forms" asp-action="Index">Forms</a></li>
    <li class="active">Upload & Display Logo</li>
</ul>
@await Html.PartialAsync("_Alerts")
<div class="row">
    <div class="col-lg-12">
        <div class="well">
            <form asp-action="UploadAndDisplayImage" asp-controller="Forms" method="post" class="form-horizontal" enctype="multipart/form-data" novalidate="novalidate" id="myForm">
                @await Component.InvokeAsync("ImageUpload", new { image = Model })
            </form>
        </div>
        <div class="well">
            @await Component.InvokeAsync("ImageDisplay", new { image = Model })
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script type="text/javascript">
        $(document).ready(function () {

            setFormValidation("myForm");
        })
    </script>
}